package io.github.jls97.boveda.ui.vault

import android.content.ContentResolver
import android.net.Uri
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.github.jls97.boveda.core.generator.GeneratorOptions
import io.github.jls97.boveda.core.generator.PasswordGenerator
import io.github.jls97.boveda.core.vault.VaultEntry
import io.github.jls97.boveda.core.vault.VaultSettings
import io.github.jls97.boveda.session.OperationResult
import io.github.jls97.boveda.session.VaultSession
import io.github.jls97.boveda.session.VaultState
import io.github.jls97.boveda.ui.components.readBackup
import io.github.jls97.boveda.ui.components.writeBackup
import io.github.jls97.boveda.ui.lock.LockViewModel
import io.github.jls97.boveda.ui.otp.RecoveryCodePurpose
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.launch
import java.util.UUID
import javax.crypto.Cipher

sealed interface Route {
    data object EntryList : Route

    data class Detail(val entryId: String) : Route

    data class Edit(val entryId: String?) : Route

    data class Generator(val forEditor: Boolean) : Route

    data object Settings : Route

    data class OtpAdd(val entryId: String) : Route

    data object OtpScan : Route

    data class OtpRecoveryCode(val purpose: RecoveryCodePurpose) : Route

    data object OtpRecover : Route
}

/** What the edit form holds. `toString` hides the values. */
data class EntryDraft(
    val id: String? = null,
    val title: String = "",
    val username: String = "",
    val password: String = "",
    val url: String = "",
    val notes: String = "",
    val autofillTargets: List<String> = emptyList(),
) {
    override fun toString() = "EntryDraft(id=$id)"
}

/**
 * State of the unlocked screens. The ViewModel outlives a lock, so it forgets the navigation,
 * the edit form and the generated password as soon as the vault locks.
 */
class VaultViewModel(
    private val session: VaultSession,
    private val contentResolver: ContentResolver,
) : ViewModel() {
    val backStack = mutableStateListOf<Route>(Route.EntryList)
    var query by mutableStateOf("")
    var draft by mutableStateOf(EntryDraft())
    var generatorOptions by mutableStateOf(GeneratorOptions())
        private set
    var generated by mutableStateOf("")
        private set
    var busy by mutableStateOf(false)
        private set

    val resumeTicks: StateFlow<Int> = session.resumeTicks

    private val _messages = Channel<String>(Channel.BUFFERED)
    val messages: Flow<String> = _messages.receiveAsFlow()

    /** The rollback warning is shown once per unlock. */
    private var integrityWarned = false

    init {
        viewModelScope.launch {
            session.state.collect { state ->
                if (state !is VaultState.Unlocked) {
                    forgetEverything()
                } else if (state.integrityWarning && !integrityWarned) {
                    integrityWarned = true
                    message(
                        "El archivo de la bóveda no es el último que se guardó en este teléfono. Si no has " +
                            "restaurado una copia, revisa tus entradas y vuelve a guardar una copia nueva.",
                    )
                }
            }
        }
    }

    private fun forgetEverything() {
        backStack.clear()
        backStack.add(Route.EntryList)
        query = ""
        draft = EntryDraft()
        generated = ""
        busy = false
        integrityWarned = false
    }

    private val unlockedData get() = (session.state.value as? VaultState.Unlocked)?.data

    private val settings: VaultSettings get() = unlockedData?.settings ?: VaultSettings()

    // region Navigation

    fun navigate(route: Route) {
        backStack.add(route)
    }

    /** Returns false when already on the first screen. */
    fun back(): Boolean {
        if (backStack.size <= 1) return false
        backStack.removeAt(backStack.lastIndex)
        return true
    }

    fun backToList() {
        backStack.clear()
        backStack.add(Route.EntryList)
    }

    /** Goes back until the current screen matches [predicate], or to the first screen. */
    fun popTo(predicate: (Route) -> Boolean) {
        while (backStack.size > 1 && !predicate(backStack.last())) backStack.removeAt(backStack.lastIndex)
    }

    // endregion

    // region Entries

    fun newEntry() {
        draft = EntryDraft()
        navigate(Route.Edit(entryId = null))
    }

    fun editEntry(entry: VaultEntry) {
        draft = EntryDraft(entry.id, entry.title, entry.username, entry.password, entry.url, entry.notes, entry.autofillTargets)
        navigate(Route.Edit(entry.id))
    }

    fun saveDraft() {
        val current = draft
        if (current.title.isBlank()) {
            message("Ponle un nombre a la entrada.")
            return
        }
        val existing = current.id?.let { id -> unlockedData?.entries?.find { it.id == id } }
        val now = System.currentTimeMillis()
        val entry = VaultEntry(
            id = current.id ?: UUID.randomUUID().toString(),
            title = current.title.trim(),
            username = current.username.trim(),
            password = current.password,
            url = current.url.trim(),
            notes = current.notes,
            createdAt = existing?.createdAt ?: now,
            updatedAt = now,
            autofillTargets = current.autofillTargets,
            // The 2FA secret is edited from its own screens and never goes through the form.
            otp = existing?.otp,
        )
        launchBusy {
            when (val result = session.saveEntry(entry)) {
                OperationResult.Success -> {
                    back()
                    if (current.id == null) navigate(Route.Detail(entry.id))
                    draft = EntryDraft()
                    message("Guardado.")
                }
                is OperationResult.Failure -> message(result.message)
                else -> message("No se pudo guardar.")
            }
        }
    }

    fun deleteEntry(id: String) {
        launchBusy {
            when (val result = session.deleteEntry(id)) {
                OperationResult.Success -> {
                    backToList()
                    message("Entrada eliminada.")
                }
                is OperationResult.Failure -> message(result.message)
                else -> message("No se pudo eliminar.")
            }
        }
    }

    fun copy(label: String, value: String) {
        val seconds = settings.clipboardClearSeconds
        session.clipboard.copy(value, seconds)
        // With auto-lock "on leaving the app", locking clears the clipboard before the timer.
        val until = if (settings.autoLockSeconds == 0) "al salir de la app" else "en $seconds s"
        message("$label copiado. Se borrará del portapapeles $until.")
    }

    // endregion

    // region Generator

    fun openGenerator(forEditor: Boolean) {
        regenerate()
        navigate(Route.Generator(forEditor))
    }

    fun updateGeneratorOptions(options: GeneratorOptions) {
        generatorOptions = options
        regenerate()
    }

    fun regenerate() {
        generated = if (PasswordGenerator.canGenerate(generatorOptions)) PasswordGenerator.generate(generatorOptions) else ""
    }

    fun useGeneratedPassword() {
        draft = draft.copy(password = generated)
        back()
    }

    // endregion

    // region Settings

    fun setAutoLock(seconds: Int) = updateSettings(settings.copy(autoLockSeconds = seconds))

    fun setClipboardClear(seconds: Int) = updateSettings(settings.copy(clipboardClearSeconds = seconds))

    private fun updateSettings(newSettings: VaultSettings) {
        launchBusy {
            val result = session.updateSettings(newSettings)
            if (result is OperationResult.Failure) message(result.message)
        }
    }

    fun changeMasterPassword(current: String, newPassword: String, confirmation: String, onSuccess: () -> Unit) {
        val problem = LockViewModel.masterPasswordProblem(newPassword, confirmation)
        if (problem != null) {
            message(problem)
            return
        }
        val hadBiometric = (session.state.value as? VaultState.Unlocked)?.biometricEnabled == true
        launchBusy {
            when (val result = session.changeMasterPassword(current.toCharArray(), newPassword.toCharArray())) {
                OperationResult.Success -> {
                    onSuccess()
                    message(
                        "Contraseña maestra cambiada con una clave de cifrado nueva. Haz una copia nueva: las " +
                            "anteriores siguen abriéndose con la contraseña antigua." +
                            if (hadBiometric) " La huella se ha desactivado; vuelve a activarla si quieres." else "",
                    )
                }
                OperationResult.WrongPassword -> message("La contraseña actual no es correcta.")
                is OperationResult.Failure -> message(result.message)
                is OperationResult.Throttled -> message("Espera antes de volver a intentarlo.")
                else -> message("No se pudo cambiar la contraseña.")
            }
        }
    }

    fun expectExternalActivity() = session.expectExternalActivity()

    fun exportBackup(uri: Uri) {
        launchBusy {
            val backup = session.exportBackup()
            when {
                backup == null -> message("La bóveda está bloqueada.")
                writeBackup(contentResolver, uri, backup) -> message("Copia cifrada guardada.")
                else -> message("No se pudo escribir el archivo.")
            }
        }
    }

    fun restoreBackup(uri: Uri, password: String) {
        launchBusy {
            val backup = readBackup(contentResolver, uri)
            if (backup == null) {
                message("No se pudo leer el archivo.")
                return@launchBusy
            }
            when (val result = session.restoreBackup(backup, password.toCharArray())) {
                OperationResult.Success, is OperationResult.Restored -> {
                    backToList()
                    val passwordNote = if ((result as? OperationResult.Restored)?.masterPasswordChanged == true) {
                        " La contraseña maestra es ahora la de la copia."
                    } else {
                        ""
                    }
                    message("Copia restaurada.$passwordNote La huella se ha desactivado; vuelve a activarla si quieres.")
                }
                OperationResult.WrongPassword -> message("La contraseña de la copia no es correcta.")
                OperationResult.WrongCurrentPassword -> message("La contraseña maestra actual no es correcta.")
                is OperationResult.Failure -> message(result.message)
                is OperationResult.Throttled -> message("Espera antes de volver a intentarlo.")
            }
        }
    }

    fun biometricEnrollmentCipher(): Cipher? = session.biometricEnrollmentCipher()

    fun enableBiometric(authorizedCipher: Cipher) {
        launchBusy {
            when (val result = session.enableBiometric(authorizedCipher)) {
                OperationResult.Success -> message("Desbloqueo con huella activado.")
                is OperationResult.Failure -> message(result.message)
                else -> message("No se pudo activar la huella.")
            }
        }
    }

    fun disableBiometric() {
        session.disableBiometric()
        message("Desbloqueo con huella desactivado.")
    }

    fun lock() = session.lock()

    // endregion

    fun message(text: String) {
        _messages.trySend(text)
    }

    private fun launchBusy(block: suspend () -> Unit) {
        if (busy) return
        busy = true
        viewModelScope.launch {
            try {
                block()
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                message("Error inesperado.")
            } finally {
                busy = false
            }
        }
    }
}
