package io.github.jls97.boveda.ui.vault

import android.content.ContentResolver
import android.net.Uri
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import io.github.jls97.boveda.core.crypto.wipe
import io.github.jls97.boveda.core.generator.GeneratorOptions
import io.github.jls97.boveda.core.generator.PasswordGenerator
import io.github.jls97.boveda.core.otp.RecoveryCode
import io.github.jls97.boveda.core.vault.VaultData
import io.github.jls97.boveda.core.vault.VaultEntry
import io.github.jls97.boveda.core.vault.VaultSettings
import io.github.jls97.boveda.data.BackupLog
import io.github.jls97.boveda.data.BackupStatus
import io.github.jls97.boveda.session.OperationResult
import io.github.jls97.boveda.session.VaultSession
import io.github.jls97.boveda.session.VaultState
import io.github.jls97.boveda.ui.components.CloudAuthorities
import io.github.jls97.boveda.ui.components.deleteDocument
import io.github.jls97.boveda.ui.components.readBackup
import io.github.jls97.boveda.ui.components.writeBackup
import io.github.jls97.boveda.ui.lock.LockViewModel
import io.github.jls97.boveda.ui.otp.RecoveryCodePurpose
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.launch
import java.util.UUID
import javax.crypto.Cipher

sealed interface Route {
    data object EntryList : Route

    data class Detail(val entryId: String) : Route

    data class Edit(val entryId: String?) : Route

    data class Generator(val forEditor: Boolean) : Route

    data object Settings : Route

    data class OtpAdd(val entryId: String) : Route

    data object OtpScan : Route

    data class OtpRecoveryCode(val purpose: RecoveryCodePurpose) : Route

    data object OtpRecover : Route
}

/** What the edit form holds. `toString` hides the values. */
data class EntryDraft(
    val id: String? = null,
    val title: String = "",
    val username: String = "",
    val password: String = "",
    val url: String = "",
    val notes: String = "",
    val autofillTargets: List<String> = emptyList(),
) {
    override fun toString() = "EntryDraft(id=$id)"
}

/**
 * State of the unlocked screens. The ViewModel outlives a lock, so it forgets the navigation,
 * the edit form and the generated password as soon as the vault locks.
 */
class VaultViewModel(
    private val session: VaultSession,
    private val contentResolver: ContentResolver,
    private val backupLog: BackupLog,
) : ViewModel() {
    val backStack = mutableStateListOf<Route>(Route.EntryList)
    var query by mutableStateOf("")
    var draft by mutableStateOf(EntryDraft())
    var generatorOptions by mutableStateOf(GeneratorOptions())
        private set
    var generated by mutableStateOf("")
        private set
    var busy by mutableStateOf(false)
        private set

    val resumeTicks: StateFlow<Int> = session.resumeTicks

    /** Fecha de la última copia verificada y cambios desde entonces (B-38). */
    val backupStatus: StateFlow<BackupStatus> = backupLog.status

    private val _messages = Channel<String>(Channel.BUFFERED)
    val messages: Flow<String> = _messages.receiveAsFlow()

    /** Copia ya sellada a la espera de que el usuario elija dónde guardarla, y sus entradas. */
    private var pendingBackup: ByteArray? = null
    private var pendingBackupEntries = 0

    /** La bóveda se bloqueó con el selector de destino abierto: la copia se descartó sin escribirse. */
    private var exportInterrupted = false

    /** Último contenido publicado estando desbloqueada, para contar cambios entre publicaciones. */
    private var lastSeenData: VaultData? = null

    /** El aviso de retroceso del archivo se muestra una vez por desbloqueo. */
    private var integrityWarned = false

    init {
        viewModelScope.launch {
            session.state.collect { state ->
                if (state is VaultState.Unlocked) {
                    trackChanges(state.data)
                    if (state.integrityWarning && !integrityWarned) {
                        integrityWarned = true
                        message(
                            "El archivo de la bóveda no es el último que se guardó en este teléfono. Si no has " +
                                "restaurado una copia, revisa tus entradas y vuelve a guardar una copia nueva.",
                        )
                    }
                } else {
                    forgetEverything()
                }
            }
        }
    }

    /**
     * Cada publicación con datos distintos a los anteriores (dentro de la misma sesión desbloqueada)
     * es un guardado o borrado que la última copia no recoge. Al desbloquear no cuenta.
     */
    private fun trackChanges(data: VaultData) {
        val previous = lastSeenData
        lastSeenData = data
        if (previous != null && previous != data) backupLog.recordChange()
        if (exportInterrupted) {
            exportInterrupted = false
            message("La bóveda se bloqueó mientras elegías dónde guardar la copia: no se guardó ninguna. Vuelve a exportarla.")
        }
    }

    private fun forgetEverything() {
        backStack.clear()
        backStack.add(Route.EntryList)
        query = ""
        draft = EntryDraft()
        generated = ""
        busy = false
        lastSeenData = null
        integrityWarned = false
        if (pendingBackup != null) {
            discardPendingBackup()
            exportInterrupted = true
        }
    }

    private val unlockedData get() = (session.state.value as? VaultState.Unlocked)?.data

    private val settings: VaultSettings get() = unlockedData?.settings ?: VaultSettings()

    // region Navigation

    fun navigate(route: Route) {
        backStack.add(route)
    }

    /** Returns false when already on the first screen. */
    fun back(): Boolean {
        if (backStack.size <= 1) return false
        forgetSecretsOf(backStack.removeAt(backStack.lastIndex))
        return true
    }

    fun backToList() {
        while (backStack.isNotEmpty()) forgetSecretsOf(backStack.removeAt(backStack.lastIndex))
        backStack.add(Route.EntryList)
    }

    /** Goes back until the current screen matches [predicate], or to the first screen. */
    fun popTo(predicate: (Route) -> Boolean) {
        while (backStack.size > 1 && !predicate(backStack.last())) forgetSecretsOf(backStack.removeAt(backStack.lastIndex))
    }

    /**
     * Al abandonar una pantalla sin guardar, lo que tenía en memoria se olvida ya, no solo al
     * bloquear (I-37): el borrador del editor y la contraseña generada. Volver del generador al
     * editor conserva el borrador, que sigue en pantalla.
     */
    private fun forgetSecretsOf(route: Route) {
        when (route) {
            is Route.Edit -> draft = EntryDraft()
            is Route.Generator -> generated = ""
            else -> Unit
        }
    }

    /** Escribir en la búsqueda cuenta como interacción para el autobloqueo (I-31). */
    fun updateQuery(text: String) {
        session.touch()
        query = text
    }

    /** Escribir en el editor cuenta como interacción para el autobloqueo (I-31). */
    fun updateDraft(newDraft: EntryDraft) {
        session.touch()
        draft = newDraft
    }

    // endregion

    // region Entries

    fun newEntry() {
        draft = EntryDraft()
        navigate(Route.Edit(entryId = null))
    }

    fun editEntry(entry: VaultEntry) {
        draft = EntryDraft(entry.id, entry.title, entry.username, entry.password, entry.url, entry.notes, entry.autofillTargets)
        navigate(Route.Edit(entry.id))
    }

    fun saveDraft() {
        val current = draft
        if (current.title.isBlank()) {
            message("Ponle un nombre a la entrada.")
            return
        }
        val existing = current.id?.let { id -> unlockedData?.entries?.find { it.id == id } }
        val now = System.currentTimeMillis()
        val entry = VaultEntry(
            id = current.id ?: UUID.randomUUID().toString(),
            title = current.title.trim(),
            username = current.username.trim(),
            password = current.password,
            url = current.url.trim(),
            notes = current.notes,
            createdAt = existing?.createdAt ?: now,
            updatedAt = now,
            autofillTargets = current.autofillTargets,
            // The 2FA secret is edited from its own screens and never goes through the form.
            otp = existing?.otp,
        )
        launchBusy {
            when (val result = session.saveEntry(entry)) {
                OperationResult.Success -> {
                    back()
                    if (current.id == null) navigate(Route.Detail(entry.id))
                    draft = EntryDraft()
                    message("Guardado.")
                }
                is OperationResult.Failure -> message(result.message)
                else -> message("No se pudo guardar.")
            }
        }
    }

    fun deleteEntry(id: String) {
        launchBusy {
            when (val result = session.deleteEntry(id)) {
                OperationResult.Success -> {
                    backToList()
                    message("Entrada eliminada.")
                }
                is OperationResult.Failure -> message(result.message)
                else -> message("No se pudo eliminar.")
            }
        }
    }

    /** [label] solo se usa en el aviso al usuario; el clip lleva siempre la etiqueta neutra «Bóveda» (I-42). */
    fun copy(label: String, value: String) {
        val seconds = settings.clipboardClearSeconds
        session.clipboard.copy(value, seconds)
        // Con «Al salir de la app», el bloqueo borra el portapapeles antes de que venza el temporizador.
        val until = if (settings.autoLockSeconds == 0) "al salir de la app" else "en $seconds s"
        message("$label copiado. Se borrará del portapapeles $until.")
    }

    // endregion

    // region Generator

    fun openGenerator(forEditor: Boolean) {
        regenerate()
        navigate(Route.Generator(forEditor))
    }

    fun updateGeneratorOptions(options: GeneratorOptions) {
        generatorOptions = options
        regenerate()
    }

    fun regenerate() {
        generated = if (PasswordGenerator.canGenerate(generatorOptions)) PasswordGenerator.generate(generatorOptions) else ""
    }

    fun useGeneratedPassword() {
        draft = draft.copy(password = generated)
        back()
    }

    // endregion

    // region Settings

    fun setAutoLock(seconds: Int) = updateSettings(settings.copy(autoLockSeconds = seconds))

    fun setClipboardClear(seconds: Int) = updateSettings(settings.copy(clipboardClearSeconds = seconds))

    /** Guarda [newSettings] tal cual. Si relajan la seguridad, la pantalla pide antes la contraseña maestra. */
    fun updateSettings(newSettings: VaultSettings) {
        launchBusy {
            val result = session.updateSettings(newSettings)
            if (result is OperationResult.Failure) message(result.message)
        }
    }

    /**
     * Vuelve a pedir la contraseña maestra antes de una operación sensible: [onVerified] solo se
     * llama si es la correcta, y ya con [busy] a false para que pueda lanzar su propia operación.
     */
    fun verifyMasterPassword(password: String, onVerified: () -> Unit) {
        if (busy) return
        busy = true
        viewModelScope.launch {
            val verified = try {
                session.verifyMasterPassword(password.toCharArray())
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                false
            } finally {
                busy = false
            }
            if (verified) onVerified() else message("La contraseña maestra no es correcta.")
        }
    }

    fun changeMasterPassword(current: String, newPassword: String, confirmation: String, onSuccess: () -> Unit) {
        val problem = LockViewModel.masterPasswordProblem(newPassword, confirmation)
        if (problem != null) {
            message(problem)
            return
        }
        val hadBiometric = (session.state.value as? VaultState.Unlocked)?.biometricEnabled == true
        launchBusy {
            when (val result = session.changeMasterPassword(current.toCharArray(), newPassword.toCharArray())) {
                OperationResult.Success -> {
                    onSuccess()
                    suggestBackup(
                        "Contraseña maestra cambiada con una clave de cifrado nueva: las copias anteriores " +
                            "siguen abriéndose con la contraseña antigua." +
                            if (hadBiometric) " La huella se ha desactivado; vuelve a activarla si quieres." else "",
                    )
                }
                OperationResult.WrongPassword -> message("La contraseña actual no es correcta.")
                is OperationResult.Failure -> message(result.message)
                is OperationResult.Throttled -> message("Espera antes de volver a intentarlo.")
                else -> message("No se pudo cambiar la contraseña.")
            }
        }
    }

    fun expectExternalActivity() = session.expectExternalActivity()

    /**
     * Primer paso de la exportación (M-10): sella la copia AHORA, con la bóveda abierta, y la
     * retiene (es solo texto cifrado) mientras el usuario elige el destino; [onReady] abre el
     * selector. Así el bloqueo por inactividad durante el selector no deja un archivo vacío.
     */
    fun prepareExport(onReady: () -> Unit) {
        launchBusy {
            discardPendingBackup()
            val backup = session.exportBackup()
            if (backup == null) {
                message("La bóveda está bloqueada.")
                return@launchBusy
            }
            pendingBackup = backup
            pendingBackupEntries = unlockedData?.entries?.size ?: 0
            onReady()
        }
    }

    /** El selector no llegó a abrirse: la copia sellada se olvida. */
    fun discardPendingBackup() {
        pendingBackup?.wipe()
        pendingBackup = null
        pendingBackupEntries = 0
    }

    /**
     * Segundo paso, al volver del selector. Escribe la copia retenida, la relee, comprueba la
     * longitud y la verifica con [VaultSession.verifyExportedBackup]; si algo falla borra el
     * documento para no dejar un .bvd vacío o dañado. Si la bóveda se bloqueó entretanto la copia
     * ya se descartó y solo queda borrar el archivo vacío que creó el sistema.
     */
    fun finishExport(uri: Uri?) {
        val backup = pendingBackup
        val entries = pendingBackupEntries
        pendingBackup = null
        pendingBackupEntries = 0
        if (uri == null) {
            backup?.wipe()
            return
        }
        // EXTRA_LOCAL_ONLY es solo una pista al selector: un destino en la nube conocido se rechaza (B-42).
        if (CloudAuthorities.isCloud(uri.authority)) {
            backup?.wipe()
            exportInterrupted = false
            viewModelScope.launch {
                val deleted = deleteDocument(contentResolver, uri)
                message(
                    "Ese destino es un servicio en la nube y la copia no se ha guardado" +
                        (if (deleted) "." else "; borra el archivo vacío que quedó.") +
                        " Elige el almacenamiento del teléfono o un USB conectado.",
                )
            }
            return
        }
        if (backup == null) {
            val interrupted = exportInterrupted
            exportInterrupted = false
            viewModelScope.launch {
                val deleted = deleteDocument(contentResolver, uri)
                message(
                    (if (interrupted) "La bóveda se bloqueó mientras elegías dónde guardar la copia: " else "La exportación se interrumpió: ") +
                        "no se guardó ninguna" +
                        (if (deleted) " y el archivo vacío se ha borrado." else "; borra el archivo vacío que quedó.") +
                        " Vuelve a exportarla.",
                )
            }
            return
        }
        launchBusy {
            try {
                val verified = writeBackup(contentResolver, uri, backup) && verifyWritten(uri, backup)
                if (verified) {
                    backupLog.recordVerifiedBackup(System.currentTimeMillis())
                    message("Copia verificada ($entries ${if (entries == 1) "entrada" else "entradas"}, ${(backup.size + 1023) / 1024} KB).")
                } else {
                    val deleted = deleteDocument(contentResolver, uri)
                    message(
                        if (deleted) {
                            "La copia no se pudo escribir o verificar y el archivo se ha borrado. Prueba en otra carpeta."
                        } else {
                            "La copia no se pudo escribir o verificar. Borra ese archivo: no sirve. Prueba en otra carpeta."
                        },
                    )
                }
            } finally {
                backup.wipe()
            }
        }
    }

    /** Relee el documento recién escrito y comprueba longitud, contenido y autenticación con la DEK. */
    private suspend fun verifyWritten(uri: Uri, expected: ByteArray): Boolean {
        val readBack = try {
            readBackup(contentResolver, uri)
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            null
        } ?: return false
        try {
            if (readBack.size != expected.size || !readBack.contentEquals(expected)) return false
            return session.verifyExportedBackup(readBack)
        } finally {
            readBack.wipe()
        }
    }

    /** Un cambio que deja obsoletas las copias anteriores: se avisa ahora y se recuerda hasta la próxima copia. */
    fun suggestBackup(reason: String) {
        backupLog.requestBackup(reason)
        message("$reason Haz una copia de seguridad ahora.")
    }

    fun restoreBackup(uri: Uri, password: String) {
        launchBusy {
            val backup = readBackup(contentResolver, uri)
            if (backup == null) {
                message("No se pudo leer el archivo.")
                return@launchBusy
            }
            when (val result = session.restoreBackup(backup, password.toCharArray())) {
                OperationResult.Success, is OperationResult.Restored -> {
                    backToList()
                    val passwordNote = if ((result as? OperationResult.Restored)?.masterPasswordChanged == true) {
                        " La contraseña maestra es ahora la de la copia."
                    } else {
                        ""
                    }
                    message("Copia restaurada.$passwordNote La huella se ha desactivado; vuelve a activarla si quieres.")
                }
                OperationResult.WrongPassword -> message("La contraseña de la copia no es correcta.")
                OperationResult.WrongCurrentPassword -> message("La contraseña maestra actual no es correcta.")
                is OperationResult.Failure -> message(result.message)
                is OperationResult.Throttled -> message("Espera antes de volver a intentarlo.")
            }
        }
    }

    fun biometricEnrollmentCipher(): Cipher? = session.biometricEnrollmentCipher()

    /** Cipher de la huella ya activada, para confirmar con ella una operación sensible en vez de con la contraseña. */
    fun biometricUnlockCipher(): Cipher? = session.biometricUnlockCipher()

    fun enableBiometric(authorizedCipher: Cipher) {
        launchBusy {
            when (val result = session.enableBiometric(authorizedCipher)) {
                OperationResult.Success -> message("Desbloqueo con huella activado.")
                is OperationResult.Failure -> message(result.message)
                else -> message("No se pudo activar la huella.")
            }
        }
    }

    fun disableBiometric() {
        session.disableBiometric()
        message("Desbloqueo con huella desactivado.")
    }

    fun lock() = session.lock()

    // endregion

    // region 2FA

    /** Comprueba que [typed] sigue siendo el código de recuperación 2FA de la bóveda. Solo dice si acierta. */
    fun checkOtpRecoveryCode(typed: String) {
        val code = RecoveryCode.normalize(typed)
        if (code == null) {
            message("El código de recuperación tiene 20 caracteres, en 4 grupos de 5.")
            return
        }
        launchBusy {
            try {
                message(
                    if (session.checkOtpRecoveryCode(code)) {
                        "El código de recuperación es correcto: el papel sigue valiendo."
                    } else {
                        "Ese no es el código de recuperación de esta bóveda. Revisa lo que apuntaste."
                    },
                )
            } finally {
                code.wipe()
            }
        }
    }

    // endregion

    fun message(text: String) {
        _messages.trySend(text)
    }

    private fun launchBusy(block: suspend () -> Unit) {
        if (busy) return
        busy = true
        viewModelScope.launch {
            try {
                block()
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                message("Error inesperado.")
            } finally {
                busy = false
            }
        }
    }
}

/**
 * True si [proposed] deja la bóveda más expuesta que [current]: el bloqueo automático tarda más
 * (0, «al salir de la app», es el más estricto) o el portapapeles se borra más tarde. Pasar a un
 * valor más estricto, o no cambiar nada, no cuenta.
 */
fun relaxesSecurity(current: VaultSettings, proposed: VaultSettings): Boolean =
    proposed.autoLockSeconds > current.autoLockSeconds ||
        proposed.clipboardClearSeconds > current.clipboardClearSeconds
