package io.github.jls97.boveda.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * Colores semánticos de Contraseñora (tema claro y oscuro). Generado desde tokens/tokens.json.
 * Uso: ContrasenoraTheme.colors.textPrimary, .brandPrimary, .totpRingFill…
 */
@Immutable
data class ContrasenoraColors(
    val bgCanvas: Color,
    val bgSurface: Color,
    val bgRaised: Color,
    val bgSunken: Color,
    val bgInverse: Color,
    val bgScrim: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val textDisabled: Color,
    val textInverse: Color,
    val textOnBrand: Color,
    val textOnAccent: Color,
    val textLink: Color,
    val borderSubtle: Color,
    val borderDefault: Color,
    val borderStrong: Color,
    val borderFocus: Color,
    val brandPrimary: Color,
    val brandPrimaryHover: Color,
    val brandPrimaryPressed: Color,
    val brandPrimarySubtle: Color,
    val brandOnPrimary: Color,
    val brandOnPrimarySubtle: Color,
    val accentDefault: Color,
    val accentHover: Color,
    val accentSubtle: Color,
    val accentOn: Color,
    val successFg: Color,
    val successBg: Color,
    val successBorder: Color,
    val dangerFg: Color,
    val dangerBg: Color,
    val dangerBorder: Color,
    val dangerSolid: Color,
    val dangerOnSolid: Color,
    val warningFg: Color,
    val warningBg: Color,
    val warningBorder: Color,
    val infoFg: Color,
    val infoBg: Color,
    val infoBorder: Color,
    val totpRingTrack: Color,
    val totpRingFill: Color,
    val totpRingUrgent: Color,
    val totpCode: Color,
    val brassDefault: Color,
    val brassText: Color,
    /** Colores del medidor de fuerza, índice 0 (muy débil) a 4 (muy fuerte). */
    val strength: List<Color>,
    val strengthTrack: Color,
    val isDark: Boolean,
)

val LightContrasenoraColors = ContrasenoraColors(
    bgCanvas = Color(0xFFFAF5FB),
    bgSurface = Color(0xFFFFFFFF),
    bgRaised = Color(0xFFFFFFFF),
    bgSunken = Color(0xFFF1ECF2),
    bgInverse = Color(0xFF1F161F),
    bgScrim = Color(0x8F1F161F),
    textPrimary = Color(0xFF1F161F),
    textSecondary = Color(0xFF564C57),
    textTertiary = Color(0xFF6F6770),
    textDisabled = Color(0xFFAEA6AF),
    textInverse = Color(0xFFFAF5FB),
    textOnBrand = Color(0xFFFFFFFF),
    textOnAccent = Color(0xFF1F161F),
    textLink = Color(0xFF6A2C70),
    borderSubtle = Color(0xFFE2D9E2),
    borderDefault = Color(0xFFCBC2CC),
    borderStrong = Color(0xFF8B838C),
    borderFocus = Color(0xFF925C97),
    brandPrimary = Color(0xFF6A2C70),
    brandPrimaryHover = Color(0xFF5A2060),
    brandPrimaryPressed = Color(0xFF450F4A),
    brandPrimarySubtle = Color(0xFFFDE5FE),
    brandOnPrimary = Color(0xFFFFFFFF),
    brandOnPrimarySubtle = Color(0xFF5A2060),
    accentDefault = Color(0xFFF2A2BD),
    accentHover = Color(0xFFDA90A9),
    accentSubtle = Color(0xFFFEE7EE),
    accentOn = Color(0xFF1F161F),
    successFg = Color(0xFF2F6A51),
    successBg = Color(0xFFE2FFF0),
    successBorder = Color(0xFFAAD0BD),
    dangerFg = Color(0xFFB02A43),
    dangerBg = Color(0xFFFFF4F4),
    dangerBorder = Color(0xFFFEACB1),
    dangerSolid = Color(0xFFB02A43),
    dangerOnSolid = Color(0xFFFFFFFF),
    warningFg = Color(0xFF6E4600),
    warningBg = Color(0xFFFFF5EA),
    warningBorder = Color(0xFFF0BB76),
    infoFg = Color(0xFF36598E),
    infoBg = Color(0xFFF2F7FE),
    infoBorder = Color(0xFFAEC7EE),
    totpRingTrack = Color(0xFFE2D9E2),
    totpRingFill = Color(0xFFB0862F),
    totpRingUrgent = Color(0xFFB02A43),
    totpCode = Color(0xFF1F161F),
    brassDefault = Color(0xFFB0862F),
    brassText = Color(0xFF674A01),
    strength = listOf(Color(0xFFB02A43), Color(0xFFB87A0A), Color(0xFFB0862F), Color(0xFF6A9A83), Color(0xFF2F6A51)),
    strengthTrack = Color(0xFFE2D9E2),
    isDark = false,
)

val DarkContrasenoraColors = ContrasenoraColors(
    bgCanvas = Color(0xFF190E1A),
    bgSurface = Color(0xFF261927),
    bgRaised = Color(0xFF332434),
    bgSunken = Color(0xFF140A15),
    bgInverse = Color(0xFFFAF5FB),
    bgScrim = Color(0xB2080309),
    textPrimary = Color(0xFFFAF5FB),
    textSecondary = Color(0xFFCBC2CC),
    textTertiary = Color(0xFFAEA6AF),
    textDisabled = Color(0xFF6F6770),
    textInverse = Color(0xFF1F161F),
    textOnBrand = Color(0xFF1F161F),
    textOnAccent = Color(0xFF1F161F),
    textLink = Color(0xFFF2A2BD),
    borderSubtle = Color(0xFF483A49),
    borderDefault = Color(0xFF564C57),
    borderStrong = Color(0xFF8B838C),
    borderFocus = Color(0xFFF2A2BD),
    brandPrimary = Color(0xFFF2A2BD),
    brandPrimaryHover = Color(0xFFFECDDC),
    brandPrimaryPressed = Color(0xFFDA90A9),
    brandPrimarySubtle = Color(0xFF3A2440),
    brandOnPrimary = Color(0xFF1F161F),
    brandOnPrimarySubtle = Color(0xFFFECDDC),
    accentDefault = Color(0xFFF2A2BD),
    accentHover = Color(0xFFFECDDC),
    accentSubtle = Color(0xFF3A2440),
    accentOn = Color(0xFF1F161F),
    successFg = Color(0xFFAAD0BD),
    successBg = Color(0xFF16271F),
    successBorder = Color(0xFF2F6A51),
    dangerFg = Color(0xFFFEACB1),
    dangerBg = Color(0xFF33161D),
    dangerBorder = Color(0xFF921632),
    dangerSolid = Color(0xFFF0858E),
    dangerOnSolid = Color(0xFF1F161F),
    warningFg = Color(0xFFF0BB76),
    warningBg = Color(0xFF2E2112),
    warningBorder = Color(0xFF6E4600),
    infoFg = Color(0xFFAEC7EE),
    infoBg = Color(0xFF161F33),
    infoBorder = Color(0xFF36598E),
    totpRingTrack = Color(0xFF483A49),
    totpRingFill = Color(0xFFE8BF73),
    totpRingUrgent = Color(0xFFF0858E),
    totpCode = Color(0xFFFAF5FB),
    brassDefault = Color(0xFFE8BF73),
    brassText = Color(0xFFE8BF73),
    strength = listOf(Color(0xFFF0858E), Color(0xFFF0BB76), Color(0xFFE8BF73), Color(0xFF8AB5A0), Color(0xFFAAD0BD)),
    strengthTrack = Color(0xFF483A49),
    isDark = true,
)
